/* Camada conectada: resultados operacionais vêm exclusivamente das APIs AIDP. */
(()=>{'use strict';window.COURTROOM_LIVE=true;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const KEY='courtroom-aidp-live-v2';let saved={results:{}};try{saved=Object.assign(saved,JSON.parse(sessionStorage.getItem(KEY)||'{}'));}catch{}
const save=()=>sessionStorage.setItem(KEY,JSON.stringify(saved));let step=1,generation=0,poll=null,busy=false,payload=null,error='',layer='bronze',asset='sql',script='load';
const refresh=document.createElement('button');refresh.id='aidp-refresh';refresh.textContent='Atualizar AIDP';$('.toolbar').prepend(refresh);refresh.onclick=()=>load();
const newCase=document.createElement('button');newCase.textContent='Nova sessão';newCase.id='aidp-new-session';$('.toolbar').prepend(newCase);newCase.onclick=()=>{sessionStorage.removeItem(KEY);localStorage.removeItem('data-courtroom-web-v3');location.href=location.pathname+'#1';location.reload();};
const explanations={
  1:{intro:'Você é o júri. Os personagens consultam recursos reais do AIDP. O caso Aurora usa dados fictícios.'},
  3:{intro:'Consulte os indicadores da preparação para comparar os dois dias. Qual deve ser o primeiro passo da investigação?',points:['Compare os indicadores retornados pelo AIDP.','Escolha uma estratégia para investigar.','A explicação aparece somente na próxima etapa.']},
  4:{intro:'Confira as fontes registradas no ambiente: catálogo relacional, tabela de pagamentos e volume documental.',case:'Os nomes, estados e arquivos desta bancada vêm da API do AIDP.'},
  5:{intro:'Execute a preparação no compute Spark e confira as camadas bronze, silver e gold.',points:['O CSV bruto fica no volume do caso.','O workflow remove duplicatas e registros inválidos.','Os indicadores são calculados no AIDP.'],case:'As contagens são lidas da saída da última execução concluída. Uma execução com falha permanece visível no histórico.'},
  6:{intro:'Leia os metadados e as permissões retornados pelo catálogo.',case:'A aplicação usa a identidade OCI configurada. Trocar um rótulo na tela não troca as permissões reais.'},
  7:{intro:'Acompanhe três tarefas reais: carregar, validar e agregar. Inspecione o código salvo no workspace.',points:['Três scripts Python são executados no compute Spark.','Carregar → validar → agregar, com dependências reais.','Inspecione o código e o histórico do workflow.'],case:'O estado de cada tarefa vem da API de workflows. A tarefa seguinte depende do sucesso da anterior.'},
  8:{title:'Byte consulta os pagamentos.',intro:'Uma ferramenta SQL de leitura compara cartão e Pix na tabela do catálogo tdcsp.',points:['A ferramenta executa uma consulta fixa de leitura.','Cartão e Pix são comparados na mesma consulta.','Byte informa os números e a origem, sem emitir o veredito.'],case:'A resposta e os rastros vêm da execução real do agente dc_byte.'},
  9:{intro:'Íris pesquisa a base de conhecimento. Você também pode abrir os documentos do volume.',case:'Compare a resposta do agente com as fontes que ele cita.'},
  10:{intro:'Teste o escopo do agente e inspecione os rastros retornados pelo AIDP.',case:'O teste mostra o comportamento observado e as ferramentas disponíveis. Não representa troca de identidade nem configuração automática de guardrails.'},
  12:{intro:'Agora Atlas recebe as respostas reais de Byte e Íris e avalia o dossiê.',case:'Se faltarem provas essenciais, a resposta deve ser inconclusiva. A conclusão não executa correções.'}
};
for(const [n,patch] of Object.entries(explanations))Object.assign(window.COURTROOM_CONTENT.scenes[Number(n)-1],patch,{notes:patch.intro+' '+(patch.case||'')+' Os resultados operacionais são consultados no AIDP; se a consulta falhar, explique a falha sem completar dados.'});
for(const item of window.COURTROOM_CONTENT.agenda){window.COURTROOM_CONTENT.scenes[item.slide-1].notes+=`\n\nCondução (${item.duration} min): ${item.activity}`;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw Error('Abra esta aplicação pelo iniciar-demo-real.cmd, em http://127.0.0.1:4178.');}if(!r.ok)throw Error(d.error||'Falha de conexão com o AIDP');return d;}
const btn=(action,text,attr='',cls='ghost')=>`<button type="button" class="${cls}" data-live="${action}" ${attr} ${busy?'disabled':''}>${text}</button>`;
const stamp=()=>payload?.fetchedAt?`<p class="live-stamp">AIDP · consultado às ${esc(new Date(payload.fetchedAt).toLocaleTimeString('pt-BR'))}</p>`:'';
function panel(title,body){return `<section class="panel aidp-panel"><div class="panel-head"><h2>${title}</h2><span class="badge">AIDP REAL</span></div>${error?`<div class="output warning" role="alert">${esc(error)}<p>Nenhum resultado simulado foi usado.</p>${btn('refresh','Tentar novamente')}</div>`:''}${body}${stamp()}</section>`;}
function table(rows){return `<div class="table-wrap"><table><thead><tr><th>Dia</th><th>Método</th><th>Tentativas</th><th>Aprovações</th><th>Receita</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.dia)}</td><td>${esc(r.metodo)}</td><td>${esc(r.tentativas)}</td><td>${esc(r.aprovados)}</td><td>${money(r.receita)}</td></tr>`).join('')}</tbody></table></div>`;}
function cards(rows){return `<div class="live-resources">${rows.map(r=>`<article class="output"><b>${esc(r.label||r.name)}</b>${r.error?`<p class="live-error">Não foi possível consultar: ${esc(r.error)}</p>`:`<p>${esc(r.name||'')}${r.state?` · <strong>${esc(r.state)}</strong>`:''}</p>${r.key?`<small>${esc(r.key)}</small>`:''}${r.items?r.items.map(x=>`<p>${esc(x.name)} · ${esc(x.state||x.type||'')}</p>`).join(''):''}${r.files?r.files.map(x=>`<p>${esc(x.name)} <small>${esc(x.type)}</small></p>`).join(''):''}`}</article>`).join('')}</div>`;}
function voteRegistered(){try{return JSON.parse(localStorage.getItem('data-courtroom-web-v3'))?.finalVote!==null&&JSON.parse(localStorage.getItem('data-courtroom-web-v3'))?.finalVote!==undefined;}catch{return false;}}
// Renderização restrita: conteúdo externo sempre escapado, sem HTML ou links ativos.
function responseMarkup(text){
 const inline=t=>esc(t).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
 const lines=String(text||'').split(/\r?\n/);let out='',list=false,quote=false;
 const close=()=>{if(list){out+='</ul>';list=false;}if(quote){out+='</blockquote>';quote=false;}};
 for(let i=0;i<lines.length;i++){
  const l=lines[i].trim();if(!l){close();continue;}
  if(l.startsWith('|')&&/^\|?[\s:|\-]+\|?$/.test((lines[i+1]||'').trim())){
   close();const cells=x=>x.trim().replace(/^\||\|$/g,'').split('|').map(t=>t.trim());out+='<div class="table-wrap"><table><thead><tr>'+cells(l).map(x=>'<th>'+inline(x)+'</th>').join('')+'</tr></thead><tbody>';i++;
   while(i+1<lines.length&&lines[i+1].trim().startsWith('|'))out+='<tr>'+cells(lines[++i]).map(x=>'<td>'+inline(x)+'</td>').join('')+'</tr>';
   out+='</tbody></table></div>';continue;
  }
  if(/^#{1,6}\s/.test(l)){close();out+='<h3>'+inline(l.replace(/^#{1,6}\s+/,''))+'</h3>';continue;}
  if(/^[-*_]{3,}$/.test(l)){close();out+='<hr>';continue;}
  if(/^(\*\*)?Refer[eê]ncia[s]?:/i.test(l)){close();out+='<details class="response-reference"><summary>Referência retornada pelo AIDP</summary><p>'+inline(l)+'</p></details>';continue;}
  if(/^>\s?/.test(l)){if(list){out+='</ul>';list=false;}if(!quote){out+='<blockquote>';quote=true;}out+='<p>'+inline(l.replace(/^>\s?/,''))+'</p>';continue;}
  if(/^(?:[-*]|\d+[.)])\s/.test(l)){if(quote){out+='</blockquote>';quote=false;}if(!list){out+='<ul>';list=true;}out+='<li>'+inline(l.replace(/^(?:[-*]|\d+[.)])\s+/,''))+'</li>';continue;}
  close();out+='<p>'+inline(l)+'</p>';
 }close();return out;
}
function responseView(r,name){return `<article class="agent-answer" data-agent="${esc(name)}"><header><span class="badge">${esc({byte:'EVIDÊNCIA SQL',iris:'EVIDÊNCIAS DOCUMENTAIS',atlas:'PARECER DO ATLAS',control:'RESULTADO DO TESTE'}[name]||'RESPOSTA AIDP')}</span><span>Retorno real do AIDP</span></header><div class="response-reading">${responseMarkup(r.text)}</div><details class="response-original"><summary>Dados da execução</summary><p class="live-stamp">${esc(r.createdAt?new Date(r.createdAt).toLocaleString('pt-BR'):'Horário não informado')} · ${(Number(r.elapsedMs||0)/1000).toFixed(1)} s · sessão ${esc(r.sessionKey||'não informada')}</p>${btn('original','Baixar resposta original',`data-agent="${esc(name)}"`)}</details></article>`;}
function agentBody(name){const r=saved.results[name];if(name==='atlas'&&!voteRegistered())return '<p>Registre o voto na etapa 11 antes de consultar Atlas.</p>';
return `<p>${name==='atlas'?'O dossiê enviado contém somente as respostas obtidas nesta sessão.':'Execute o agente para obter evidências do ambiente.'}</p>${btn('agent',busy?'Consultando AIDP…':'Consultar '+({byte:'Byte',iris:'Íris',atlas:'Atlas'}[name]),`data-agent="${name}"`,'primary')}${r?responseView(r,name):'<p class="hint">Nenhuma resposta obtida nesta sessão. A consulta não usa gabarito local.</p>'}`;}
function workflow(p){return `<p class="live-stamp">Execução ${esc(p.key||'não iniciada')}</p><div class="pipeline">${['carregar','validar','agregar'].map(n=>{const t=p.tasks?.find(t=>t.name===n);return `<div class="node ${['SUCCESS','SUCCEEDED'].includes(t?.state?.status)?'done':t?.state?.status==='FAILED'?'failed':''}"><b>${n}</b><small>${esc(t?.state?.status||'AGUARDANDO')}</small></div>`;}).join('<span class="arrow">→</span>')}</div><p><strong>${esc(p.state?.status||'SEM EXECUÇÃO')}</strong> ${esc((p.state?.stateMessage||'').split('\n').filter(Boolean).at(-1)?.slice(0,250)||'')}</p><div class="button-row">${[5,7].includes(step)?btn('start','Executar workflow no AIDP','','primary'):''}${btn('refresh','Atualizar estado')}</div><details><summary>Histórico real</summary>${(p.history||[]).map(r=>`<p>${esc(r.state?.status)} · ${esc(new Date(r.created).toLocaleString('pt-BR'))}<br><small>${esc(r.key)}</small></p>`).join('')}</details>`;}
function render(){const area=$('.workarea'),d=payload?.data;refresh.disabled=busy||[3,11,13,15,16].includes(step);newCase.disabled=busy||[3,11,13].includes(step);$('.session-label').textContent=error?'AIDP · consulta indisponível':'AIDP real · dados fictícios';
if([11,13].includes(step))return;
if(step===15){area.innerHTML=`<section class="panel"><div class="panel-head"><h2>Visita ao ambiente real</h2><span class="badge">10 MINUTOS</span></div><ol class="session-tour"><li><b>30–32 · Workspace</b><p>Localizar o projeto, seus arquivos e scripts.</p></li><li><b>32–34 · Catálogo</b><p>Reconhecer tabela, volume e documentos.</p></li><li><b>34–37 · Compute e workflow</b><p>Conferir recursos, tarefas e histórico de execução.</p></li><li><b>37–40 · Agentes</b><p>Ver ferramentas SQL/RAG e a base de conhecimento.</p></li></ol><p class="hint">A apresentadora alterna para a aba OCI/Workbench já autenticada.</p></section>`;return;}
if(step===16){area.innerHTML=`<section class="panel"><div class="panel-head"><h2>A conversa continua</h2><span class="badge">20 MINUTOS</span></div><p>Podemos voltar a uma fonte, abrir o código ou discutir outra forma de resolver o problema.</p><div class="output"><b>Para reproduzir depois</b><p>Notebook, dados fictícios, Terraform da instância e orientações de preparação.</p><a class="primary" href="materiais.html" target="_blank" rel="noopener">Abrir materiais ↗</a></div><p class="hint">O kit explica o que está automatizado e o que ainda exige configuração. A participação nesta sessão não depende de uma conta OCI.</p></section>`;return;}

if(step===1){let status=$('#aidp-home-status');if(!status){status=document.createElement('p');status.id='aidp-home-status';status.className='case-box';$('.hero section').append(status);}status.textContent=error?'AIDP indisponível: '+error:d?'Recursos consultados no AIDP. Missão pronta para investigar.':'Conferindo o ambiente AIDP…';return;}
if(step===3){const grid=$('.stat-grid');if(grid){if(d){const totals={};for(const r of d.rows){const x=totals[r.dia]??={total:0,approved:0,revenue:0};x.total+=Number(r.tentativas);x.approved+=Number(r.aprovados);x.revenue+=Number(r.receita);}const days=Object.keys(totals).sort();grid.innerHTML=days.map(day=>`<div class="stat"><small>${esc(day)}</small><div class="big-number">${money(totals[day].revenue)}</div><span>${totals[day].approved} aprovações</span></div>`).join('');$('.metrics-line').innerHTML=`<span>${esc(totals[days[0]]?.total)} tentativas por dia no recorte</span><span>Execução ${esc(d.runKey.slice(0,8))}</span>`;}else{grid.innerHTML=`<p>${esc(error||'Consultando indicadores no AIDP…')}</p>`;$('.metrics-line').innerHTML='';}}return;}
if(step===14){let wrap=$('#aidp-finish');if(!wrap){wrap=document.createElement('div');wrap.id='aidp-finish';area?.append(wrap);}wrap.innerHTML=panel('Registro real da missão',`${d?workflow(d):'<p>Consultando o histórico do AIDP…</p>'}${btn('report','Baixar relatório real')}`);return;}
if(!area)return;let body='';if([8,12].includes(step)){area.innerHTML=panel(step===8?'Byte · SQL':'Atlas · parecer',agentBody(step===8?'byte':'atlas'));return;}
if(step===9){body=agentBody('iris')+`<details><summary>Documentos lidos diretamente do volume</summary>${d?.documents?d.documents.map(x=>`<details class="output"><summary>${esc(x.name)}</summary><small>${esc(x.path)}</small><pre class="real-response">${esc(x.text)}</pre></details>`).join(''):'<p>Carregando documentos…</p>'}</details>`;area.innerHTML=panel('Íris · RAG e fontes',body);return;}
if(step===10){const r=saved.results.control;body=`<p>Enviar uma solicitação ao agente e observar sua resposta real:</p><div class="button-row">${btn('control','Consultar indicadores','data-test="read"')}${btn('control','Pedir alteração','data-test="write"')}${btn('control','Testar instrução no documento','data-test="injection"')}</div>${r?responseView(r,"control"):''}<details><summary>Rastros recebidos do AIDP</summary>${Array.isArray(d)&&d.length?d.slice().reverse().map(x=>`<article class="output"><b>${esc(x.label)} · ${(x.elapsedMs/1000).toFixed(1)} s</b><small> · ${esc(x.sessionKey.slice(0,8))}</small>${x.spans.map(s=>`<p>${esc(s.name)} · ${esc(s.status)} · ${Math.round(s.durationMs)} ms</p>`).join('')}</article>`).join(''):'<p>Nenhuma execução de agente neste servidor ainda.</p>'}</details><p class="hint">Os rastros mostram operações e tempos, não raciocínio interno. Os testes de escopo não alteram as permissões da identidade OCI.</p>`;area.innerHTML=panel('Escopo e observabilidade',body);return;}
if(!d){area.innerHTML=panel('Consultando AIDP',error?'':'<p>Aguardando a API do ambiente…</p>');return;}
switch(step){case 2:body=`<div class="tour-launch"><div><b>Conheça o caminho com os personagens</b><p>Uma parada por componente, com Byte, Íris e Atlas.</p></div><button class="primary" data-workspace-tour>Começar o caminho →</button></div>`+cards(d.resources);break;
case 4:body='<div class="reveal-banner"><b>Resposta da etapa anterior: cruzar números e documentos.</b></div>'+cards(d.sources)+btn('refresh','Verificar fontes no AIDP','','primary');break;
case 5:body=`<div class="layer-tabs">${['bronze','silver','gold'].map(x=>btn('layer',x.toUpperCase(),`data-layer="${x}"`,x===layer?'selected':'ghost')).join('')}</div><p class="live-stamp">Última preparação concluída: ${esc(new Date(d.generatedAt).toLocaleString('pt-BR'))}</p>${layer==='bronze'?`<div class="big-number">${d.received}</div><p>Registros recebidos do CSV no volume.</p><div class="table-wrap"><table><thead><tr><th>Tentativa</th><th>Dia</th><th>Valor</th></tr></thead><tbody>${d.sample.map(r=>`<tr><td>${esc(r.tentativa_id)}</td><td>${esc(r.dia)}</td><td>${r.valor===null?'Inválido':money(r.valor)}</td></tr>`).join('')}</tbody></table></div><p class="hint">Amostra do dado bruto retornada pelo Spark.</p>`:layer==='silver'?`<div class="big-number">${d.valid}</div><p>${d.duplicates} duplicatas e ${d.invalid} registro inválido removidos no Spark.</p>`:table(d.rows)}<div class="button-row">${btn('start','Reexecutar preparação no AIDP','','primary')}${btn('refresh','Atualizar resultado')}</div>`;break;
case 6:body=`<div class="tabs">${['sql','bronze','silver','gold'].map(x=>btn('asset',x.toUpperCase(),`data-asset="${x}"`,x===asset?'selected':'ghost')).join('')}</div><div class="code">${esc(d.key)}</div><p>Estado: <b>${esc(d.state||'Não informado')}</b></p><p>Responsável retornado: ${esc(d.owner)}</p><details open><summary>Colunas e tipos</summary><pre class="real-response">${esc(JSON.stringify(d.columns,null,2))}</pre></details><details><summary>Permissões retornadas pela API</summary><pre class="real-response">${esc(JSON.stringify(d.permissions,null,2))}</pre></details><p class="hint">A leitura acima foi feita com a identidade OCI configurada. Não há alternância fictícia entre analista e visitante.</p>`;break;
case 7:body=workflow(d)+`<details><summary>Código salvo no workspace</summary><div class="button-row">${btn('script','Carregar','data-file="load"')}${btn('script','Validar','data-file="validate"')}${btn('script','Agregar','data-file="aggregate"')}</div><pre id="live-code" class="real-response">Selecione uma tarefa para consultar o arquivo no AIDP.</pre></details>`;break;}
area.innerHTML=panel({2:'Mapa do ambiente',4:'Fontes reais',5:'Preparação no Spark',6:'Catálogo e acesso',7:'Workflow real'}[step],body);
window.dispatchEvent(new Event('resize'));
}
async function load(){clearTimeout(poll);const ticket=++generation;payload=null;error='';render();if([8,11,12,13,15,16].includes(step))return;const op={1:'overview',2:'overview',3:'metrics',4:'sources',5:'metrics',6:'catalog',7:'pipeline',9:'documents',10:'traces',14:'pipeline'}[step];if(!op)return;try{const r=await api(op==='traces'?'/api/traces':'/api/live?op='+op+(op==='catalog'?'&asset='+asset:''));if(ticket!==generation)return;payload=r;render();if(step===7&&['PENDING','RUNNING','QUEUED','IN_PROGRESS','BLOCKED'].includes(r.data.state?.status))poll=setTimeout(load,6000);}catch(e){if(ticket!==generation)return;error=e.message;render();}}
async function execute(path,body){busy=true;error='';render();try{return await api(path,body);}catch(e){error=e.message;return null;}finally{busy=false;}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-live]');if(!b)return;e.preventDefault();const action=b.dataset.live;
if(action==='original'){const r=saved.results[b.dataset.agent];if(r){const u=URL.createObjectURL(new Blob([r.text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='resposta-'+b.dataset.agent+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}return;}if(action==='refresh'){await load();return;}if(action==='layer'){layer=b.dataset.layer;await load();return;}if(action==='asset'){asset=b.dataset.asset;await load();return;}
if(action==='start'){const r=await execute('/api/pipeline',{stage:step});if(r){location.hash='7';await load();}else render();return;}
if(action==='agent'){const name=b.dataset.agent;if(name==='atlas'&&(!saved.results.byte||!saved.results.iris)){error='Consulte Byte na etapa 8 e Íris na etapa 9 antes de enviar o dossiê.';render();return;}const r=await execute('/api/demo',{agent:name,stage:step,dossier:name==='atlas'?{byte:saved.results.byte.text,iris:saved.results.iris.text}:undefined});if(r){saved.results[name]=r;save();}render();return;}
if(action==='control'){const r=await execute('/api/control',{stage:10,test:b.dataset.test});if(r){saved.results.control=r;save();await load();}else render();return;}
if(action==='script'){try{const r=await api('/api/live?op=notebook&file='+b.dataset.file);if($('#live-code'))$('#live-code').textContent=r.data.path+'\n\n'+r.data.text;}catch(e){error=e.message;render();}return;}
if(action==='report')await report();});
async function report(){try{const [workflow,metrics,traces]=await Promise.all([api('/api/live?op=pipeline'),api('/api/live?op=metrics'),api('/api/traces')]);const blob=new Blob([JSON.stringify({title:'Data Courtroom — execução real AIDP',generatedAt:new Date().toISOString(),simulation:false,workflow,metrics,traces,responses:saved.results},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='data-courtroom-aidp-real.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){error=e.message;render();}}
// Impede que atalhos antigos abram resultados locais sobre a camada conectada.
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(['report','download','trace','dossier','setup'].includes(b.dataset.action)){e.preventDefault();e.stopImmediatePropagation();if([3,11,13].includes(step))return;if(['report','download'].includes(b.dataset.action))report();else location.hash=b.dataset.action==='trace'?'10':b.dataset.action==='dossier'?'9':'2';}},true);
window.addEventListener('courtroom:render',()=>{step=Number(location.hash.slice(1)||1);load();});
})();
