/* Caminho didático guiado pelos personagens; não executa operações cloud. */
(()=>{'use strict';
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const people={byte:'Byte',iris:'Íris',atlas:'Atlas'};
const stops=[
 {name:'Workspace',verb:'Organizar',person:'atlas',question:'Onde vamos organizar nosso trabalho?',speech:'Antes de começar, precisamos de um lugar para reunir o código e o plano do projeto.',definition:'O workspace organiza arquivos, notebooks e workflows e os associa aos recursos de execução.',icon:'⌘',tokens:['Arquivos','Código','Workflows'],detail:'É uma organização lógica. Não é a máquina que executa o código nem significa que todos os dados foram copiados para dentro dele.',labels:['Workspace']},
 {name:'Arquivos e conhecimento',verb:'Guardar e buscar',person:'iris',question:'Onde estão os documentos?',speech:'Guardar o arquivo e encontrar o trecho certo são duas tarefas diferentes.',definition:'O volume organiza os arquivos. A base de conhecimento prepara conteúdo para recuperar trechos relevantes.',icon:'▤',tokens:['Arquivos no volume','Base preparada','Busca de trechos'],detail:'Na demo, Íris usa uma ferramenta RAG para recuperar contexto. Também podemos abrir o arquivo completo e conferir a fonte.',labels:['Base documental']},
 {name:'Catálogo',verb:'Localizar',person:'iris',question:'Como encontro a tabela certa?',speech:'Preciso saber onde a informação está e o que cada coluna representa.',definition:'O catálogo ajuda a localizar e entender os ativos por seus nomes, estrutura e metadados.',icon:'▦',tokens:['Catálogo','Schema','Tabela'],detail:'O catálogo pode referenciar uma fonte externa. Cadastrar um ativo não valida automaticamente seus valores nem concede acesso a qualquer pessoa.',labels:['Catálogo SQL']},
 {name:'Compute Spark',verb:'Processar',person:'byte',question:'Quem executa o tratamento?',speech:'O código diz o que fazer. O compute fornece os recursos para executar.',definition:'O compute Spark executa código de processamento: carregar registros, validar e agregar, por exemplo.',icon:'{ }',tokens:['Código','Compute Spark','Resultado'],detail:'A preparação cria tabelas próprias do laboratório. Byte consulta a tabela externa em tdcsp por outro caminho; ele não lê automaticamente a gold produzida aqui.',labels:['Compute de preparação']},
 {name:'Workflow',verb:'Coordenar',person:'byte',question:'Como repetimos isso na ordem certa?',speech:'Se a validação depende da carga, essa ordem precisa estar definida.',definition:'O workflow organiza tarefas e dependências. Cada execução tem seu próprio estado e histórico.',icon:'⤳',tokens:['Carregar','Validar','Agregar'],detail:'A definição do workflow coordena as tarefas. O compute executa o código. Uma tarefa concluída não garante que toda regra de negócio foi bem definida.',labels:[]},
 {name:'AI Compute',verb:'Executar agentes',person:'atlas',question:'E onde os agentes entram?',speech:'Temos instruções e ferramentas. Precisamos de recursos para executar os agentes.',definition:'O AI Compute fornece recursos para executar agentes que usam modelos e ferramentas.',icon:'✧',tokens:['Agentes','Modelos','Ferramentas'],detail:'Compute não é o modelo. Nesta aplicação, Byte usa SQL, Íris usa RAG e a aplicação envia as respostas a Atlas. O parecer do caso continua reservado ao slide 12, depois da votação.',labels:['AI Compute']}
];
const dialog=document.createElement('dialog');dialog.id='workspace-tour';dialog.className='workspace-tour';dialog.setAttribute('aria-label','Caminho dos componentes com Byte, Íris e Atlas');document.body.append(dialog);
let current=0,resources=[],status='Consultando recursos…',ticket=0,opener;
function shell(){dialog.innerHTML=`<div class="journey-shell"><header class="journey-header"><div><small>DATA COURTROOM / CONHEÇA O AMBIENTE</small><h2>Vamos conhecer o caminho?</h2><p>Uma parada, uma função. Byte, Íris e Atlas acompanham você.</p></div><button data-journey="close">Voltar ao slide ×</button></header><section class="journey-scene" aria-live="polite"></section><div class="journey-route"><div class="journey-rail" aria-hidden="true"><span class="journey-progress"></span><span class="journey-traveler"><img src="assets/atlas.png" alt=""></span></div><nav aria-label="Paradas do caminho">${stops.map((s,i)=>`<button data-journey="stop" data-index="${i}"><span>${i+1}</span><b>${s.name}</b></button>`).join('')}</nav></div><footer class="journey-footer"><span>Percurso de explicação · não representa fluxo de dados nem inicia execuções</span><div><button data-journey="previous">← Voltar</button><button class="primary" data-journey="next">Próxima parada →</button></div></footer></div>`;show(0);}
function show(n){current=Math.max(0,Math.min(stops.length-1,n));const s=stops[current];dialog.dataset.station=String(current);dialog.dataset.guide=s.person;dialog.style.setProperty('--journey-position',(current/(stops.length-1)*100)+'%');dialog.querySelector('.journey-traveler img').src='assets/'+s.person+'.png';dialog.querySelectorAll('[data-journey=stop]').forEach((b,i)=>{b.setAttribute('aria-current',i===current?'step':'false');b.classList.toggle('passed',i<current);});dialog.querySelector('.journey-scene').innerHTML=`<div class="journey-character"><span class="journey-guide-label">SEU GUIA NESTA PARADA</span><div class="journey-portrait"><img src="assets/${s.person}.png" alt="${people[s.person]}"><span class="journey-character-name">${people[s.person]}</span></div><p class="journey-speech">“${s.speech}”</p><small>Fala didática do personagem</small></div><div class="journey-lesson"><span class="journey-eyebrow">PARADA ${current+1} / ${stops.length} · ${s.verb.toUpperCase()}</span><h3>${s.question}</h3><div class="journey-component"><span aria-hidden="true">${s.icon}</span><div><b>${s.name}</b><p>${s.definition}</p></div></div><div class="journey-tokens">${s.tokens.map(t=>`<span>${t}</span>`).join('')}</div><details class="journey-more"><summary>Entender um pouco mais</summary><p>${s.detail}</p></details><details class="journey-resources"><summary>Conferir no ambiente AIDP</summary><div></div><button data-journey="refresh">Atualizar estados</button></details></div>`;dialog.querySelector('[data-journey=previous]').disabled=current===0;dialog.querySelector('[data-journey=next]').textContent=current===stops.length-1?'Concluir visita ✓':'Próxima parada →';updateResources();}
function updateResources(){const s=stops[current];dialog.querySelector('.journey-resources>div').innerHTML=s.labels.length?s.labels.map(label=>{const r=resources.find(x=>x.label===label);return `<p><b>${esc(label)}:</b> ${r?r.error?'Indisponível: '+esc(r.error):esc(r.name)+' · '+esc(r.state||'estado não informado'):esc(status)}</p>`;}).join(''):'<p>O workflow deste laboratório é acompanhado na etapa 7 da apresentação, com suas tarefas, estados e histórico.</p>';}
async function refresh(){const id=++ticket;resources=[];status='Consultando recursos…';updateResources();try{const r=await fetch('/api/live?op=overview');const d=await r.json();if(!r.ok)throw Error(d.error||'Consulta indisponível');if(id!==ticket||!dialog.open)return;resources=d.data.resources;status='Recurso não retornado.';}catch(e){if(id!==ticket||!dialog.open)return;status='Consulta indisponível: '+e.message;}updateResources();}
function close(){ticket++;dialog.close();opener?.focus();}
function next(){if(current===stops.length-1)close();else show(current+1);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-workspace-tour]');if(!b)return;opener=b;resources=[];shell();dialog.showModal();dialog.querySelector('[data-journey=close]').focus();refresh();});dialog.addEventListener('click',e=>{const b=e.target.closest('[data-journey]');if(!b)return;switch(b.dataset.journey){case 'close':close();break;case 'stop':show(Number(b.dataset.index));break;case 'next':next();break;case 'previous':show(current-1);break;case 'refresh':refresh();break;}});dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.addEventListener('keydown',e=>{if(!dialog.open)return;e.stopImmediatePropagation();if(e.key==='ArrowRight'){e.preventDefault();next();}if(e.key==='ArrowLeft'){e.preventDefault();show(current-1);}},true);window.addEventListener('hashchange',()=>{if(dialog.open)close();});
})();
