'use strict';
const {request}=require('./provisionamento/aidp-rest.cjs');const cfg=require('./provisionamento/pipeline-resources.json');const zlib=require('zlib');
const WS='/workspaces/'+cfg.workspaceKey,VOLUME='default.tdc_courtroom.evidencias',ROOT='/Volumes/default/tdc_courtroom/evidencias',KB='legacy:/knowledgeBases/default.tdc_courtroom.kb_aurora_evidencias';
const get=async route=>(await request('GET',route)).data;
const summary=x=>({name:x.displayName||x.name,key:x.key,state:x.lifecycleState||(typeof x.state==='string'?x.state:x.state?.status),type:x.type,description:x.description,updated:x.timeUpdated,created:x.timeCreated});
async function many(entries){const results=await Promise.allSettled(entries.map(async([name,route])=>({name,data:await get(route)})));return results.map((r,i)=>r.status==='fulfilled'?r.value:{name:entries[i][0],error:r.reason.message});}
function decode(output){return (output.data||[]).map(x=>{let b=(x.isBase64||x.isbase64)?Buffer.from(x.value||'','base64'):Buffer.from(x.value||'');if(x.compression==='GZIP')b=zlib.gunzipSync(b);const text=b.toString('utf8');if(x.type==='APPLICATION_JSON'){const nested=JSON.parse(text);if(nested.output?.data)return decode(nested.output);if(nested.data)return decode(nested);}return text;}).join('\n');}
async function runs(){return (await get(WS+'/jobRuns?jobKey='+cfg.jobKey+'&limit=20&sortOrder=DESC')).items.sort((a,b)=>new Date(b.timeCreated)-new Date(a.timeCreated));}
async function pipeline(runKey){const all=await runs();const key=runKey||all[0]?.key;if(!key)return {jobKey:cfg.jobKey,history:[],tasks:[]};if(!/^[a-f0-9-]{36}$/.test(key))throw Error('Identificador de execução inválido');const run=await get(WS+'/jobRuns/'+key);if(run.jobKey!==cfg.jobKey)throw Error('Execução fora do laboratório');const tasks=await Promise.all(Object.entries(run.taskToTaskRunMap||{}).map(async([name,id])=>{const t=await get(WS+'/taskRuns/'+id);return {name,key:id,state:t.state,outputKey:t.outputKey,startTime:t.startTime,endTime:t.endTime};}));return {jobKey:cfg.jobKey,key,state:run.state,created:run.timeCreated,startTime:run.startTime,endTime:run.endTime,tasks,history:all.slice(0,6).map(r=>({key:r.key,state:r.state,created:r.timeCreated}))};}
async function metrics(){const all=await runs();const successful=all.find(x=>['SUCCEEDED','SUCCESS'].includes(x.state?.status));if(!successful)throw Error('Ainda não há execução bem-sucedida do workflow. Execute a preparação na etapa 5 ou 7.');const run=await get(WS+'/jobRuns/'+successful.key);const key=run.taskToTaskRunMap?.agregar;if(!key)throw Error('A execução não possui agregação');const t=await get(WS+'/taskRuns/'+key);const out=(await request('POST',WS+'/taskRuns/'+key+'/actions/fetchOutput',{outputKey:t.outputKey})).data;const line=decode(out).split(/\r?\n/).find(x=>x.includes('COURTROOM_RESULT:'));if(!line)throw Error('O AIDP não retornou o resultado estruturado da agregação');const parsed=JSON.parse(line.slice(line.indexOf('COURTROOM_RESULT:')+17));if(parsed.stage!=='gold'||!Array.isArray(parsed.rows))throw Error('Resultado de agregação inválido');return {...parsed,runKey:run.key};}
async function readDocument(name){if(!['campanha.txt','mudanca-pagamento.txt','reconciliacao.txt'].includes(name))throw Error('Documento fora do caso');const r=await request('POST','/volumes/'+VOLUME+'/actions/downloadFile',undefined,{path:ROOT+'/'+name,accept:'*/*'});return {name,path:ROOT+'/'+name,text:typeof r.data.text==='string'?r.data.text:JSON.stringify(r.data)};}
async function live(op,params={}){let data;switch(op){case 'overview':{const r=await many([['Workspace','/workspaces/{workspace}'],['AI Compute','/workspaces/{workspace}/clusters/'+cfg.aiComputeKey],['Compute de preparação',WS+'/clusters/'+cfg.computeKey],['Catálogo SQL','/catalogs/tdcsp'],['Base documental',KB],['Agentes','/workspaces/{workspace}/agents'],['Workflow',WS+'/jobs/'+cfg.jobKey]]);data={resources:r.map(x=>({label:x.name,...(x.error?{error:x.error}:x.data.items?{items:x.data.items.filter(a=>a.displayName?.startsWith('dc_')).map(summary)}:summary(x.data))}))};break;}
case 'sources':{const r=await many([['Catálogo relacional','/catalogs/tdcsp'],['Schema SQL','/schemas/tdcsp.agent_search'],['Tabela SQL','/tables/tdcsp.agent_search.tdc_dc_pagamentos'],['Volume','/volumes/'+VOLUME],['Arquivos','/volumes/'+VOLUME+'/files?path='+encodeURIComponent(ROOT)]]);data={sources:r.map(x=>({label:x.name,...(x.error?{error:x.error}:x.data.items?{files:x.data.items.map(y=>({name:y.displayName,path:y.path,type:y.type,updated:y.timeUpdated}))}:summary(x.data))}))};break;}
case 'metrics':data=await metrics();break;
case 'catalog':{const key={sql:'tdcsp.agent_search.tdc_dc_pagamentos',bronze:'default.tdc_courtroom.dc_pagamentos_bronze',silver:'default.tdc_courtroom.dc_pagamentos_silver',gold:'default.tdc_courtroom.dc_pagamentos_gold'}[params.asset||'sql'];if(!key)throw Error('Ativo inválido');const t=await get('/tables/'+key);let permissions;try{permissions=await get('/tables/'+key+'/permissions');}catch(e){permissions={error:e.message};}data={...summary(t),key,columns:t.tableFields||t.columns||t.columnCollection||[],owner:t.createdByName||t.createdBy||t.owner||'Não informado pela API',permissions};break;}
case 'pipeline':data=await pipeline(params.runKey);break;
case 'documents':data={base:summary(await get(KB)),documents:await Promise.all(['mudanca-pagamento.txt','reconciliacao.txt','campanha.txt'].map(readDocument))};break;
case 'notebook':{const file={load:'01_carregar.py',validate:'02_validar.py',aggregate:'03_agregar.py'}[params.file||'load'];if(!file)throw Error('Arquivo inválido');const r=await request('GET',WS+'/objects/'+encodeURIComponent(cfg.folder+'/'+file),undefined,{accept:'*/*'});data={path:cfg.folder+'/'+file,text:r.data.text};break;}
case 'start':{const all=await runs();const active=all.find(r=>['PENDING','RUNNING','QUEUED','IN_PROGRESS','BLOCKED'].includes(r.state?.status));if(active)data={key:active.key,state:active.state,reused:true};else data=(await request('POST',WS+'/jobRuns',{jobKey:cfg.jobKey})).data;break;}
default:throw Error('Operação não disponível');}return {source:'AIDP',fetchedAt:new Date().toISOString(),data};}
module.exports={live,decode,pipeline};
